# Airbnb Open Data - EDA

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

In [2]:
df = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Airbnb_Open_Data.csv")
df.head(3)

C:\Users\ADITYA GUPTA\AppData\Local\Temp\ipykernel_27452\199728082.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 46.7+ MB

In [4]:
df.shape

(102599, 26)

In [5]:
df.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

In [6]:
unique_names = df['host id'].nunique()
print(f'number of unique host id: {unique_names}')
print(f' % of unique host id: {round(unique_names / df["host id"].shape[0] * 100, 2)}%')

number of unique host id: 102057
 % of unique host id: 99.47%

In [7]:
# Most host IDs are unique, so the 'host id' column is not useful for analysis and can be dropped.
# and dont not need 'id' and 'license' columns as well, so we can drop them too.
df = df.drop(columns=['host id', 'id', 'license'])

In [8]:
df.shape

(102599, 23)

In [9]:
unique_names = df['host name'].nunique()
print(f'number of unique host names: {unique_names}')
print(f'% of unique names: {round(unique_names / df["host name"].shape[0] * 100, 2)}%')
print(f'{round(unique_names / df["host name"].shape[0] * 100, 2)}% - that means we have new hosts in this year')

number of unique host names: 13190
% of unique names: 12.86%
12.86% - that means we have new hosts in this year

In [10]:
percentage_identity_verified = df['host_identity_verified'].value_counts()
print(f'{round(percentage_identity_verified / df["host_identity_verified"].shape[0] * 100, 2)}%')
print(f'\n that means 50% of unconfirmeded hosts:')

host_identity_verified
unconfirmed    49.90
verified       49.82
Name: count, dtype: float64%

 that means 50% of unconfirmeded hosts:

In [11]:
df['neighbourhood group'].value_counts()

neighbourhood group
Manhattan        43792
Brooklyn         41842
Queens           13267
Bronx             2712
Staten Island      955
brookln              1
manhatan             1
Name: count, dtype: int64

In [12]:
#case fixing
df['neighbourhood group'] = df['neighbourhood group'].str.title()
#spelling fixing
df['neighbourhood group'] = df['neighbourhood group'].replace({'Manhattan': 'Manhattan', 'Brooklyn': 'Brooklyn', 'Queens': 'Queens', 'Bronx': 'Bronx', 'Staten Island': 'Staten Island'})

In [13]:
df['neighbourhood group'].unique()

<ArrowStringArray>
[     'Brooklyn',     'Manhattan',       'Brookln',      'Manhatan',
        'Queens',             nan, 'Staten Island',         'Bronx']
Length: 8, dtype: str

In [14]:
# now we have to drop nan values from 'neighbourhood group' column
df['neighbourhood group'].isna().sum()

np.int64(29)

In [15]:
#we found 29 nans in 'neighbourhood group' column, we can fill them with 'Unknown' value
df['neighbourhood group'] = df['neighbourhood group'].fillna('Unknown')

In [16]:
df['neighbourhood group'].unique()

<ArrowStringArray>
[     'Brooklyn',     'Manhattan',       'Brookln',      'Manhatan',
        'Queens',       'Unknown', 'Staten Island',         'Bronx']
Length: 8, dtype: str

In [17]:
#hmm, lets see how many unique values we have in 'neighbourhood' column
unique_neighbourhoods = df['neighbourhood'].unique().shape[0]
print(f'number of unique neighbourhoods: {unique_neighbourhoods}')
print(f'lets see % of unique neighbourhoods: {round(unique_neighbourhoods / df["neighbourhood"].shape[0] * 100, 2)}%')

number of unique neighbourhoods: 225
lets see % of unique neighbourhoods: 0.22%

In [18]:
# nothing to clean till now, we can move to next step of analysis.

In [19]:
df.columns

Index(['NAME', 'host_identity_verified', 'host name', 'neighbourhood group',
       'neighbourhood', 'lat', 'long', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules'],
      dtype='str')

In [20]:
df[['lat', 'long']].describe()

                 lat           long
count  102591.000000  102591.000000
mean       40.728094     -73.949644
std         0.055857       0.049521
min        40.499790     -74.249840
25%        40.688740     -73.982580
50%        40.722290     -73.954440
75%        40.762760     -73.932350
max        40.916970     -73.705220

In [21]:
# there is no such big diffrence we will leave them as it is, we can move to next step of analysis.

In [22]:
df['country code'].value_counts()

country code
US    102468
Name: count, dtype: int64

In [23]:
df['country'].value_counts()

country
United States    102067
Name: count, dtype: int64

In [24]:
# as we see they both have same value so we can drop both 'country code' and 'country' columns
df = df.drop(columns=['country code', 'country'])

In [25]:
instant_bookable =df['instant_bookable'].value_counts()
print(f'{round(instant_bookable / df["instant_bookable"].shape[0] * 100, 2)}%')

instant_bookable
False    50.17
True     49.73
Name: count, dtype: float64%

In [26]:
cancelation_percentage = df['cancellation_policy'].value_counts()
print(f'{round(cancelation_percentage / df["cancellation_policy"].shape[0] * 100, 2)}')

cancellation_policy
moderate    33.47
strict      33.24
flexible    33.21
Name: count, dtype: float64

In [27]:
room_type = df['room type'].value_counts(normalize=True) * 100
print(f'{round(room_type, 2)}%')

room type
Entire home/apt    52.34
Private room       45.38
Shared room         2.17
Hotel room          0.11
Name: proportion, dtype: float64%

In [28]:
df['Construction year'].sort_values(ascending=False).head(5)

15473    2022.0
10346    2022.0
44761    2022.0
44738    2022.0
44729    2022.0
Name: Construction year, dtype: float64

In [29]:
# we have to change $ sign becoz its not a numeric value and it will creat problem in analysid
df['price'] = df['price'].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

In [30]:
df['price'].sample(5)

54111    1137.0
985       913.0
74784     658.0
76953     437.0
55675     627.0
Name: price, dtype: float64

In [31]:
df['service fee'].head(5)

0    $193
1     $28
2    $124
3     $74
4     $41
Name: service fee, dtype: str

In [32]:
#removing dollor sign from service fee column
df['service fee'] = df['service fee'].str.replace('$', '', regex=False).str.replace(',', '', regex=False).astype(float)

In [33]:
df['service fee'].head(5)

0    193.0
1     28.0
2    124.0
3     74.0
4     41.0
Name: service fee, dtype: float64

In [34]:
df.columns

Index(['NAME', 'host_identity_verified', 'host name', 'neighbourhood group',
       'neighbourhood', 'lat', 'long', 'instant_bookable',
       'cancellation_policy', 'room type', 'Construction year', 'price',
       'service fee', 'minimum nights', 'number of reviews', 'last review',
       'reviews per month', 'review rate number',
       'calculated host listings count', 'availability 365', 'house_rules'],
      dtype='str')

In [35]:
df['minimum nights'].head(5)

0    10.0
1    30.0
2     3.0
3    30.0
4    10.0
Name: minimum nights, dtype: float64

In [36]:
df['minimum nights'].isnull().sum()

np.int64(409)

In [37]:
df['minimum nights'] = df['minimum nights'].replace(np.nan, 0)
df['minimum nights'].isnull().sum()

np.int64(0)

In [38]:
df['number of reviews'].isnull().sum()

np.int64(183)

In [39]:
df['number of reviews'] = df['number of reviews'].replace(np.nan, 0)
df['number of reviews'].isnull().sum()

np.int64(0)

In [40]:
df[['last review']].head(7)

  last review
0  10/19/2021
1   5/21/2022
2         NaN
3    7/5/2019
4  11/19/2018
5   6/22/2019
6   10/5/2017

In [41]:
# converting str to datetime
df['last review'] = pd.to_datetime(df['last review'], errors='coerce')
df['last review'].sort_values(ascending=True).head(7)

69470   2012-07-11
1294    2012-07-11
69519   2012-08-10
1343    2012-08-10
1464    2012-08-25
69640   2012-08-25
69472   2012-09-05
Name: last review, dtype: datetime64[us]

In [42]:
# now we have 400 somthing null values we have to use interpolation method to fill those null values in 'last review' column
df['last review'] = df['last review'].interpolate(method='linear')
df['last review'].isnull().sum()

np.int64(0)

In [43]:
df[['reviews per month', 'review rate number']].head(5)

   reviews per month  review rate number
0               0.21                 4.0
1               0.38                 4.0
2                NaN                 5.0
3               4.64                 4.0
4               0.10                 3.0

In [44]:
df[['reviews per month', 'review rate number']].describe()

       reviews per month  review rate number
count       86720.000000       102273.000000
mean            1.374022            3.279106
std             1.746621            1.284657
min             0.010000            1.000000
25%             0.220000            2.000000
50%             0.740000            3.000000
75%             2.000000            4.000000
max            90.000000            5.000000

In [45]:
# i find review per month column is useless so i will drop it
df = df.drop(columns=['reviews per month'])

In [46]:
df['calculated host listings count'].value_counts().index[0:]

Index([  1.0,   2.0,   3.0,   4.0,   5.0,   6.0,   7.0,   8.0,   9.0,  10.0,
       327.0,  12.0,  96.0,  11.0,  13.0, 232.0,  33.0, 121.0, 208.0,  14.0,
        23.0,  91.0,  17.0,  87.0,  34.0,  52.0,  49.0,  50.0, 186.0, 103.0,
        18.0,  65.0,  15.0, 161.0,  28.0,  31.0, 102.0,  19.0,  20.0, 108.0,
        25.0,  47.0,  30.0,  37.0,  53.0,  26.0,  43.0,  48.0,  32.0,  16.0,
       171.0,  66.0,  83.0, 152.0,  24.0,  39.0, 126.0,  56.0,  27.0,  51.0,
        54.0,  21.0,  62.0,  44.0,  59.0, 332.0,  29.0, 125.0, 218.0,  45.0,
        67.0,  63.0,  58.0,  86.0,  22.0,  55.0,  46.0,  80.0],
      dtype='float64', name='calculated host listings count')

In [47]:
df['calculated host listings count'].head(5)

0    6.0
1    2.0
2    1.0
3    1.0
4    1.0
Name: calculated host listings count, dtype: float64

In [48]:
df['availability 365'].head(3)

0    286.0
1    228.0
2    352.0
Name: availability 365, dtype: float64

In [49]:
df['availability 365'].describe()

count    102151.000000
mean        141.133254
std         135.435024
min         -10.000000
25%           3.000000
50%          96.000000
75%         269.000000
max        3677.000000
Name: availability 365, dtype: float64

In [50]:
df['house_rules'].head(5)

0    Clean up and treat the home the way you'd like...
1    Pet friendly but please confirm with me if the...
2    I encourage you to use my kitchen, cooking and...
3                                                  NaN
4    Please no smoking in the house, porch or on th...
Name: house_rules, dtype: str

In [51]:
df['house_rules'].isnull().sum()

np.int64(52131)

In [52]:
# as we see the house rules column has 1000+ null values, so we can drop it as well
df = df.drop(columns=['house_rules'])

In [53]:
df.shape

(102599, 19)

In [54]:
df.sample(3)

,NAME,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,review rate number,calculated host listings count,availability 365
89036,LUXURY SUTTON PLACE RESIDENCY~DOORMAN/GYM/ELEV...,unconfirmed,Ruchi,Manhattan,Midtown,40.75936,-73.96293,False,strict,Entire home/apt,2015.0,61.0,12.0,30.0,0.0,2018-08-09,3.0,49.0,364.0
76269,Comfortable One Bedroom Apt in Prospect Heights,unconfirmed,Catherine,Brooklyn,Prospect Heights,40.67948,-73.96526,True,flexible,Entire home/apt,2008.0,244.0,49.0,30.0,11.0,2019-05-21,3.0,3.0,87.0
70590,Authentic Soho Loft (1200 sq ft),verified,Norwin,Manhattan,Tribeca,40.71976,-74.00571,False,strict,Entire home/apt,2019.0,324.0,65.0,2.0,124.0,2019-06-22,3.0,1.0,131.0

In [55]:
df[['price']].head(2)

   price
0  966.0
1  142.0

In [56]:
df['availability 365'] = pd.to_numeric(df['availability 365'], errors='coerce')

In [57]:
df['availability 365'].dtypes

dtype('float64')

In [58]:
clean_df = df.copy()
clean_df.to_csv(r'C:\Users\ADITYA GUPTA\Downloads\clean_airbnb_data.csv', index=False)