In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"C:\Users\ADITYA GUPTA\Downloads\Data\IPL_dataset.xlsx")
df.head()

,L2,L3,L6,value batsman_NA,value bowler_NA,value extras_byes,value extras_legbyes,value extras_wides,value non_striker_NA,value runs_batsman,...,balls_per_over,umpire1,umpire2,MatchID,value extras_noballs,value runs_non_boundary,L10 replacements_role,L9 replacements_role,value replacements_role,value extras_penalty
0,1,1st innings,0.1,A Chopra,DW Steyn,NaN,NaN,NaN,BJ Hodge,0,...,6,Asad Rauf,IL Howell,336010,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1st innings,0.1,A Mukund,A Chandila,NaN,NaN,NaN,CH Gayle,1,...,6,M Erasmus,K Srinath,598036,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1st innings,0.1,AB McDonald,IK Pathan,NaN,NaN,NaN,CA Pujara,0,...,6,S Asnani,S Ravi,548310,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1st innings,0.1,Abhishek Sharma,DR Sams,NaN,NaN,NaN,PK Garg,0,...,6,CB Gaffaney,N Pandit,1304111,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1st innings,0.1,Abhishek Sharma,I Sharma,NaN,NaN,NaN,MA Agarwal,0,...,6,MA Gough,Navdeep Singh,1359514.yaml,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(243793, 35)

In [4]:
df.columns

Index(['L2', 'L3', 'L6', 'value batsman_NA', 'value bowler_NA',
       'value extras_byes', 'value extras_legbyes', 'value extras_wides',
       'value non_striker_NA', 'value runs_batsman', 'value runs_extras',
       'value runs_total', 'value wicket_fielders', 'value wicket_kind',
       'value wicket_player_out', 'Winning_Team', 'MOM', 'Venue',
       'competition', 'Match_date', 'match_city', 'match_type', 'overs',
       'outcome_by', 'margin', 'balls_per_over', 'umpire1', 'umpire2',
       'MatchID', 'value extras_noballs', 'value runs_non_boundary',
       'L10 replacements_role', 'L9 replacements_role',
       'value replacements_role', 'value extras_penalty'],
      dtype='str')

In [5]:
Working_cols = [
    'Match_date',           # time trends
    'match_city',           # location analysis
    'Venue',                # ground-wise stats
    'Winning_Team',         # win/loss analysis
    'MOM',                  # Man of the Match
    'value runs_batsman',   # batting runs
    'value runs_total',     # total runs per ball
    'value runs_extras',    # extras
    'value wicket_kind',    # type of dismissal
    'value wicket_player_out',  # who got out
    'margin',               # win by how many runs/wickets
    'outcome_by',           # runs or wickets
    'competition',          # IPL season/year
    'overs',                 # over number
    'value batsman_NA',     # who is batting
    'value bowler_NA'       # who is bowling
]

df_work = df[Working_cols]

In [6]:
df.shape

(243793, 35)

In [7]:
df_work.head(2)

,Match_date,match_city,Venue,Winning_Team,MOM,value runs_batsman,value runs_total,value runs_extras,value wicket_kind,value wicket_player_out,margin,outcome_by,competition,overs,value batsman_NA,value bowler_NA
0,2008-05-08,Kolkata,Eden Gardens,Kolkata Knight Riders,SC Ganguly,0,0,0,NaN,NaN,Won by 5 runs,5.0,IPL,20,A Chopra,DW Steyn
1,2013-04-29,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,SV Samson,1,1,0,NaN,NaN,Won by 4 wickets,4.0,IPL,20,A Mukund,A Chandila

In [8]:
df_work['value wicket_kind'].value_counts()

value wicket_kind
caught                   7437
bowled                   2089
run out                  1062
lbw                       750
caught and bowled         349
stumped                   345
retired hurt               15
hit wicket                 15
retired out                 3
obstructing the field       2
Name: count, dtype: int64

In [9]:
df_work['competition'].value_counts()

competition
IPL    243793
Name: count, dtype: int64